### ISSUE TITLE
Write a post explaining why I decided to use a Github Page associated to an organization with my name

### ISSUE THREAD

**Issue by J0hnG4lt** [georvic-tur/georvic-tur.github.io#1]
## Tasks

- [ ] write a post

## References

- [ ] - https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages
- [x] - https://medium.com/@ajlehechka/why-you-should-create-a-github-organization-for-your-side-project-d7c941dbb45b
- [x] - https://stackoverflow.com/questions/40563563/custom-username-for-github-pages-but-not-a-custom-domain
- [x] - https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site
