### ISSUE TITLE
Write a first technical post about Helm and Kubernetes

### ISSUE THREAD

**Issue by J0hnG4lt** [georvic-tur/georvic-tur.github.io#3]
## Description

It would be cool to write a Helm chart for this repo: https://github.com/ThoughtWorksInc/CD4ML-Scenarios

## Tasks

- [x] Fork the repo and make it work locally with Docker.
- [ ] Write manifests for K8s and test them with Minikube.
- [ ] Parametrize these manifests for Helm.

**Comment by J0hnG4lt** [comment]
I had already forked the repo and did some changes to make it work for me: https://github.com/J0hnG4lt/CD4ML-Scenarios
